spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vanilla
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: debug
    com.github.zer0e: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
